version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-escrow-server
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/escrow-app-backend
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - .:/db_volume
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=${MYSQL_DB}
