databases:
  - name: db
    postgresMajorVersion: 15
    plan: free

services:
  - type: web
    name: app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: development
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 5000
      - key: JWT_SECRET_KEY
        value: 1a9b535f2a8c98284bbfeb9a28cff8ffbf883e41ab7c6cc0bd5444d5bdf2adc0
      - key: PG_ROOT_PASS
        fromDatabase:
          name: db
          property: connectionString
      - key: PG_USER
        fromDatabase:
          type: database
          name: db
          property: connectionString
      - key: PG_PWD
        fromDatabase:
          type: database
          name: db
          property: connectionString
      - key: PG_DB
        fromDatabase:
          type: database
          name: db
          property: connectionString
      - key: PG_HOST
        fromDatabase:
          type: database
          name: db
          property: connectionString

